name: Close Preview
on:
  pull_request:
    types:
      - closed
permissions:
  contents: read
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    permissions:
      contents: read
    steps:
      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > ./preview-id
      - name: Save data for another workflow
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: preview-id
          retention-days: 1
          path: |
            ./preview-id
